service: notablehealth
app: notablehealth-app
org: ajawchat

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: src/entry/handler.handler
    events:
      - http:
          path: /doctors/{id}
          method: get
          request:
            parameters:
              paths:
                id: false

plugins:
  - serverless-offline