service: notablehealth
app: notablehealth-app
org: ajawchat

provider:
  name: aws
  runtime: nodejs10.x

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: users/create
          method: get

plugins:
  - serverless-offline